name: Deploy Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build idb_companion
        run: |
          cd $GITHUB_WORKSPACE
          brew install protobuf
          ./idb_build.sh idb_companion build build_output

      - name: Compress idb_companion
        run: |
          tar -czf idb-companion.universal.tar.gz -C build_output .

      - name: Build idb wheel package
        run: |
          pip3 install --break-system-packages grpclib==0.4.1 wheel setuptools pyre-extensions protobuf
          FB_IDB_VERSION=0.2.3 python3 setup.py sdist bdist_wheel

      - name: Upload idb_companion Artifact
        uses: actions/upload-artifact@v4
        with:
          name: idb_companion-${{ github.sha }}
          path: ./idb-companion.universal.tar.gz

      - name: Upload idb wheel package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: idb_whl-${{ github.sha }}
          path: ./dist/fb_idb-0.2.3-py3-none-any.whl
